import { Client as CocClient } from 'clashofclans.js';
import { normalizeTag } from '../../util/helper.js';
import { Logger } from '../../util/logger.js';

/**
 * Wrapper around `clashofclans.js`. Supports either static IP-locked API tokens
 * (CLASH_API_TOKENS) or an email/password login that mints keys for the current host.
 */
export class Coc {
  public readonly client: CocClient;
  private readonly log = new Logger('Coc');
  private ready = false;

  public constructor() {
    this.client = new CocClient({ cache: true, retryLimit: 2 });
  }

  public async init(): Promise<void> {
    if (this.ready) return;

    const email = process.env.CLASH_API_EMAIL?.trim();
    const password = process.env.CLASH_API_PASSWORD?.trim();

    // Preferred path (and the right one for Railway/dynamic hosts): log in with the developer
    // account and let the library mint IP-locked keys for THIS host automatically. On every boot
    // it detects the current outbound IP and re-issues the key if the IP changed — so a Railway
    // redeploy that moves the container to a new IP just works, with no manual key juggling.
    if (email && password) {
      const keyCount = Math.min(Math.max(Number(process.env.CLASH_API_KEY_COUNT || 1), 1), 10);
      const keys = await this.client.login({
        email,
        password,
        keyName: process.env.CLASH_API_KEY_NAME || 'argon-bot',
        keyCount,
        keyDescription: 'Auto-generated by ARGON. Do not delete while the bot is running.'
      });
      this.ready = true;
      this.log.info(`Logged in to the CoC developer site — ${keys.length} key(s) active for this host's IP.`);
      return;
    }

    // Fallback: use pre-created static tokens (only works while this host keeps the IP the keys
    // were created for). Handy for local dev with a fixed IP.
    const tokens = (process.env.CLASH_API_TOKENS || '')
      .split(',')
      .map((t) => t.trim())
      .filter(Boolean);

    if (tokens.length) {
      this.client.setKeys(tokens);
      this.ready = true;
      this.log.info(`Initialized CoC client with ${tokens.length} static token(s).`);
      return;
    }

    throw new Error(
      'No Clash of Clans credentials set. Set CLASH_API_EMAIL + CLASH_API_PASSWORD (recommended), ' +
        'or CLASH_API_TOKENS for a fixed-IP host.'
    );
  }

  /** Fetch a player by tag; returns null on 404/errors. */
  public async getPlayer(tag: string) {
    try {
      return await this.client.getPlayer(normalizeTag(tag));
    } catch (error) {
      this.log.debug(`getPlayer(${tag}) failed:`, (error as Error).message);
      return null;
    }
  }

  /** Fetch a clan by tag; returns null on 404/errors. */
  public async getClan(tag: string) {
    try {
      return await this.client.getClan(normalizeTag(tag));
    } catch (error) {
      this.log.debug(`getClan(${tag}) failed:`, (error as Error).message);
      return null;
    }
  }

  /** Current war for a clan (regular). Returns null if not in war / private log. */
  public async getCurrentWar(tag: string) {
    try {
      return await this.client.getCurrentWar(normalizeTag(tag));
    } catch (error) {
      this.log.debug(`getCurrentWar(${tag}) failed:`, (error as Error).message);
      return null;
    }
  }

  public async getWarLog(tag: string) {
    try {
      return await this.client.getClanWarLog(normalizeTag(tag));
    } catch (error) {
      this.log.debug(`getWarLog(${tag}) failed:`, (error as Error).message);
      return null;
    }
  }

  /** Current CWL group for a clan. Returns null when not in a CWL season. */
  public async getCwlGroup(tag: string) {
    try {
      return await this.client.getClanWarLeagueGroup(normalizeTag(tag));
    } catch (error) {
      this.log.debug(`getCwlGroup(${tag}) failed:`, (error as Error).message);
      return null;
    }
  }

  /** Verify a player token issued in-game (Settings -> More -> API Token). */
  public async verifyPlayerToken(tag: string, token: string): Promise<boolean> {
    try {
      return await this.client.verifyPlayerToken(normalizeTag(tag), token);
    } catch (error) {
      this.log.debug(`verifyPlayerToken(${tag}) failed:`, (error as Error).message);
      return false;
    }
  }

  /** Search clans by name (used by /search). */
  public async searchClans(name: string, limit = 10) {
    try {
      return await this.client.getClans({ name, limit });
    } catch (error) {
      this.log.debug(`searchClans(${name}) failed:`, (error as Error).message);
      return null;
    }
  }
}
